name: "trace"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 0

data_type: "random-camera-datamodule"
data:
  load_type: ${system.load_type}
  batch_size: 1
  eval_camera_distance: 4.0
  camera_distance_range: [1.5, 4.0]
  light_sample_strategy: "dreamfusion3dgs"
  height: 1024
  width: 1024
  eval_height: 1024
  eval_width: 1024
  # elevation_range: [-10 , 80]
system_type: "trace-system"
system:
  load_type: 0 # 0: load from shape, 1: load from smpl; # 2: load from custom point cloud
  load_path: "" # only used when load_type == 1
  radius: ${data.eval_camera_distance}
  sh_degree: 0
  prompt_processor_type: "stable-diffusion-prompt-processor"
  # prompt_processor_type_2: "stable-diffusion-sds-bridge-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    prompt: ???
    negative_prompt: "ugly, bad anatomy, blurry, pixelated obscure, unnatural colors,
      poor lighting, dull, and unclear, cropped, lowres, low quality, artifacts, duplicate,
      morbid, mutilated, poorly drawn face, deformed, dehydrated, bad proportions,
      unfocused"

  guidance_type: "trace-guidance"
  guidance:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    pretrained_model_name_or_path_lora: "stabilityai/stable-diffusion-2-1"
    guidance_scale: 20.
    weighting_strategy: sch_bridge
    min_step_percent: 0.02
    max_step_percent: 0.98
    grad_clip: [0, 1.5, 2.0, 1000]
    stage_one_weight: 1.
    stage_two_weight: 1.
    stage_two_start_step: 700
    max_steps: ${trainer.max_steps}
    # view_dependent_prompting: false
    sqrt_anneal: true  # sqrt anneal proposed in HiFA: https://hifa-team.github.io/HiFA-site/
    use_img_loss: true  # image-space SDS proposed in HiFA: https://hifa-team.github.io/HiFA-site/
    use_dreamtime: false
    use_annealing: false
    use_src_tgt_noise: false
    evenodd: false
    pure_src_uncond: false

  loggers:
    wandb:
      enable: false
      project: 'threestudio'
      name: None

  loss:
    lambda_sds: 1.
    lambda_lora: 1.
    lambda_sparsity: 1.
    lambda_opaque: 0.0
  optimizer:
    name: Adam
    args:
      betas: [0.9, 0.99]
      eps: 1.e-15
      lr: 0.001

trainer:
  max_steps: 1700
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  val_check_interval: 100
  enable_progress_bar: true
  precision: 16-mixed

checkpoint:
  save_last: true # save at each validation time
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}
